---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://TejaswiniOpsmx:encrypted%3Agittoken%3Agittoken@github.com/TejaswiniOpsmx/404b3.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/TejaswiniOpsmx/404b3.git
  gituser: TejaswiniOpsmx
  gittoken: encrypted:gittoken:gittoken
  dynamicAccRepository: 404b3

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
